### ISSUE TITLE
VIOLATION OF TERMS AND CONDITIONS

### ISSUE THREAD

**Issue by debdutgoswami** [khacksOSS/HacktoberFestKarunya2019#127]
This repository violates Hacktoberfest 2019's Terms and Conditions.

While this repository might me good for starters but certainly, allowing to merge PRs of "hello world" shows that the main objective is to complete Hacktoberfest and claim a free t-shirt. Such behavior is highly condemned.

This repository will be taken down soon.

Regards.

**Comment by jeffin143** [comment]
Thanks @debdutgoswami , Good to see you are concerned about OSS and the terms and condition of Hacktoberfest 
I have been coding for 6 years and still remember my first line of code to be **hello world**, To keep things in perspective, Here is an article by [Geeks for Geeks](https://www.geeksforgeeks.org/writing-first-c-program-hello-world-example/) quoting 

`The “Hello World” program is the first step towards learning any programming language and also one of the simplest programs you will learn`

So, I guess It is totally ok to write or contribute a `hello world` program

The repo was created in a view of workshop/meetup conducted during Hacktoberfest and students were taught to use git and raise a PR in mere two hours of time. I guess you are aware of the face that the power of git couldn't be taught in 2 hours :)

The workshop was attended by many of the freshers who haven't interacted with computer or were from Non Cse background 

![EGWp3NMU8AA7ek4](https://user-images.githubusercontent.com/21286134/66746773-5df49980-eea0-11e9-82de-a3f47293d983.jpeg)

Let's get to some statistics too :)

```
https://github.com/khacksOSS/HacktoberFestKarunya2019/pulls/SamSergius0018
https://github.com/khacksOSS/HacktoberFestKarunya2019/pulls?q=is%3Apr+author%3ADanialmonachan11
https://github.com/khacksOSS/HacktoberFestKarunya2019/commits?author=hiruthic2002
https://github.com/khacksOSS/HacktoberFestKarunya2019/commits?author=BenvinD
```
Following were the pull request of some of the students, I couldn't find any one among them contributing hello world, I would be happy to know which PR you are talking about, Could you please point out the PR no.

```
In line with Hacktoberfest value #2 (Quantity is fun, quality is key), here are examples of the PRs that we consider to be low-quality contributions (which we discourage).

● PRs that are automated (e.g. scripted opening PRs to remove whitespace/optimize images)

● PRs that are disruptive (e.g. taking someone else's branch/commits and making a PR)

● PRs that are regarded by a project maintainer as a hindrance vs. helping

● Something that's clearly an attempt to simply +1 your PR count for October

● Last but not least, one PR to fix a typo is fine. 5 PRs to remove a stray whitespace... not. 
```

If you have reached till here, I can see that you are totally aligned with the idea **Quantity is fun, quality is key***, and hence can see your history of PR being so of high value for the community

-  Adding your name - https://github.com/CodeChefVIT/Hacktoberfest19/pull/157#issue-326335842  

- Refactoring code - https://github.com/ucalyptus/Detecting-Ships/pull/6#issue-326705059, which counts as removing a space :)

- Adding a basic function analogous to so called `hello world` program - https://github.com/microsoft/c9-python-getting-started/pull/31#issue-326572863 ( which violates 4th point )
 
I may not waste time to see more of you PR, You are free to go ahead and report this repo of violating the terms and conditions of Hacktoberfest :)

Thanks for reading all the way down, Always good to meet people who are always up and running for the community :)

**Comment by debdutgoswami** [comment]
I am sorry but I didn't actually want to report this issue here. It was for another repository. I am currently out of station so I was checking the Hacktoberfest repositories from my mobile. The issue was for a different repository which was taken down by the Hacktoberfest community. I mentioned about them on twitter too. 

It was my mistake that I didn't check the repository name before raising an issue. I am really sorry for all the trouble you went through to write the long message. I didn't report this repository either. To prove my point, here is the link to the tweet which I made. You can check that repository from my tweet.

I am really sorry for all the inconveniences caused due to my action and also for the time I wasted of yours.

Link to the tweet: https://twitter.com/debdutgoswami/status/1183489644106637312?s=20
Link of the repository I was actually talking about: https://github.com/AliceWonderland/hacktoberfest

Really sorry for spoiling your workflow. I would see to that I don't make such mistakes in the future. 

Regards.

**Comment by debdutgoswami** [comment]
@jeffin143 

Please look into the above thread and if possible could you delete the issue raised by me as it was an honest mistake on my part. :)

Regards.
